### PR TITLE
Fix Linux issues

### PR DESCRIPTION
**Pull request by foldericon**
This fixes compiling issues with Swift 3.0.2 on Linux.

### CODE REVIEW

**Comment by tristanhimmelman** [comment]
Sorry no I didn't see this! Thanks for the fix

**Comment by AnthonyOliveri** [comment]
@tristanhimmelman Is there a time frame for the next version release? I'm using Swift Package Manager, so I can't incorporate this fix into my project until a new version is released.

**Comment by foldericon** [comment]
@AnthonyOliveri `cd Packages/ObjectMapper-2.2.3 && git pull`

**Comment by tristanhimmelman** [comment]
@AnthonyOliveri I plan on releasing soon enough, however I would like to merge in a few more PRs before I do so.

**Comment by AnthonyOliveri** [comment]
@foldericon That's fine for testing, but I'm creating libraries. I can specify the dependencies but can't include the downloaded Packages as part of the libraries.

**Comment by foldericon** [comment]
@AnthonyOliveri I am not a maintainer of this project, I just tried to provide a temporal workaround. Hopefully they will add some more flexibility to SPM soon.

**Comment by tristanhimmelman** [comment]
I just created a new release with these changes `2.2.4`

**Comment by AnthonyOliveri** [comment]
It works now. Thanks @foldericon and @tristanhimmelman!

**Pull request merged**
