### PR TITLE
ImmutableMappable: Support for Two-Dimensial Arrays

### PR DESCRIPTION
**Pull request by afonsograca**
With the migration to Swift 3 I decided to switch my models to ImmutableMappables. The problem was that my 2D arrays were not being parsed, causing the map to throw. Since `Array<Array<T: Mappable>>` is one of the supported types, 
All tests are passing, even the ones I added. :)

### CODE REVIEW

**Comment by devxoul** [comment]
@afonsograca, thanks for your work, but please don't change other things. Could you please update your PR to not include unrelated changes?

**Comment by afonsograca** [comment]
@devxoul are you referring to the whitespace formatting? Sorry about that, already updated.

**Comment by devxoul** [comment]
@afonsograca you can check unrelated diffs here: https://github.com/Hearst-DD/ObjectMapper/pull/759/files

**Comment by afonsograca** [comment]
already removed the unused code. should be okay now.

**Comment by tristanhimmelman** [comment]
Thanks for your work @afonsograca. I merged this work into master via another branch where I made a few minor alterations. I'm not sure why Github did not automatically close this though...

**Pull request closed without merging**
