### PR TITLE
Update Map.swift JSONDictionary getter

### PR DESCRIPTION
**Pull request by zulkis**
Added possibility to get JSONDictionary as a root value

### CODE REVIEW

**Comment by zulkis** [comment]
I tried to explain everything in https://github.com/Hearst-DD/ObjectMapper/issues/375

**Comment by tristanhimmelman** [comment]
Hi @zulkis, I think I would prefer to just make JSONDictionary a public variable in this situation.

**Comment by zulkis** [comment]
Hi @tristanhimmelman, it is a good solution, but still it is not preventing the situation with setting with dictionary from the outside(weird situation but still possible).
Actually I prefer to modify property but in that case of setting private setter/public getter - we have setValue function in ToJSON.swift that uses JSONDictionary as internal property...

From my side - it is not so important how to get it :) More important to obtain this possibility, because I don't really want to fork it(or in case of using AlamofireObjectMapper fork both)

Thank you!

**Comment by ikesyo** [comment]
Just writing `public internal(set) var JSONDictionary` would be fine.

**Comment by zulkis** [comment]
@ikesyo, you're absolutely correct!

**Pull request closed without merging**
