### PR TITLE
Operator code cleanup

### PR DESCRIPTION
**Pull request by tapi**
Was working on #309 when I encountered some code inconsistencies that were bugging me so I fixed them.
Thought it best to keep it separate from #309. Did them a separate commits so you can cherry pick if you don't like one or the other.

### CODE REVIEW

**Comment by tapi** [comment]
`exited with 65.` 😂
Im fighting exactly this issue with CircleCI

**Comment by tristanhimmelman** [comment]
Yeah I've been seeing this too... sometimes it resolves itself by just restarting the build. I just did that, lets see if it fixes itself.

**Comment by tapi** [comment]
Passed on all but one configuration, Wish I could get that kind of success with Circle ;)

**Comment by tristanhimmelman** [comment]
Thx, these changes definitely make the code easier to read

**Comment by tapi** [comment]
No, problem. Mostly scratching my own itch ;)

**Pull request merged**
