### PR TITLE
add doc Chinese support 

### PR DESCRIPTION
**Pull request by lacklock**
add doc Chinese support

### CODE REVIEW

**Comment by ManWithBear** [comment]
Why you not translate full README?

**Comment by lacklock** [comment]
i plan when ImmutableMappable release translte it.
And Installation i think every developers can understand it ,  doesn't need to translate.
If you think it's would be better translate full content, i would finish it all.

**Comment by lacklock** [comment]
done!

**Comment by tristanhimmelman** [comment]
thanks @lacklock 👍

**Pull request merged**
