### PR TITLE
Added watchOS target, scheme, tests and updated to Xcode 7/Swift 2

### PR DESCRIPTION
**Pull request by nrbrook**
While I haven't tested yet, this doesn't produce any compile errors and should be most of the ground work for Swift 2 and watchOS. The tests can't be run as I haven't made a Swift 2 Nimble fork.

### CODE REVIEW

**Comment by robertoschwald** [comment]
I get the following error while trying to compile your fork using Carthage 0.6.5 and 0.7.4, Xcode7 Beta command-line tools:

*** Building scheme "ObjectMapper-watchOS" in ObjectMapper.xcworkspace
*** Building scheme "ObjectMapper-iOS" in ObjectMapper.xcworkspace
*** Building scheme "ObjectMapper-Mac" in ObjectMapper.xcworkspace
*** Building scheme "ObjectMapper-watchOS" in ObjectMapper.xcworkspace
Parse error: unexpected SDK key "(string)"

Carthage setup:
github "nrbrook/ObjectMapper" "swift-2"

**Comment by crayment** [comment]
Same issue - it creates the framework but Xcode 7 fails to build with `ld: framework not found ObjectMapper`.

**Comment by tristanhimmelman** [comment]
I have created another branch with Swift-2.0 support. All the tests have been updated and are running as well. I have yet to look into added watchOS support though.

https://github.com/Hearst-DD/ObjectMapper/tree/swift-2.0

**Comment by nrbrook** [comment]
Should I look into fixing these issues or is @tristanhimmelman 's branch the official one? I need watchOS support, which is just a case of duplicating the iOS targets and scheme really.

**Comment by tristanhimmelman** [comment]
@nrbrook, my new branch is the official one. I have added a watchOS target and scheme. Let me know if you have any issues. Thanks

**Pull request closed without merging**
