### PR TITLE
Swift 2.0

### PR DESCRIPTION
**Pull request by benoit-pereira-da-silva**
In swift 2.0 with Xcode7 B6, static methods are **reputed finals!**
The "static func newInstance() -> Mappable" cannot be overridden anymore.

My proposition consists to pass the map to the initializer init?(_ map: Map). When a mappable object inheritates from another mappable object it should call super before proceeding to its own mapping. This approach is consistent with NSCoder pattern.

``` swift
// MARK: Mappable

required init?(_ map: Map) {
        super.init(map)
        mapping(map)
}
```

### CODE REVIEW

**Comment by tristanhimmelman** [comment]
I am using Xcode 7 B6 as well but I am not seeing the issue you are pointing out. See https://github.com/Hearst-DD/ObjectMapper/tree/swift-2.0#subclasses for the syntax to you need use when subclassing Mappable classes.

I am, however, thinking of changing the protocol to pretty much what you are proposing. See branch protocol-update: https://github.com/Hearst-DD/ObjectMapper/tree/protocol-update.

**Comment by benoit-pereira-da-silva** [comment]
@tristanhimmelman the new protocol you are proposing is matching mine and is perfect :+1: 

Concerning my previous issue, i have understood :  i was trying to override the "static func newInstance(map: Map) -> Mappable?" as declared in the protocol : 

```swift
public protocol Mappable {
	static func newInstance(map: Map) -> Mappable?
	mutating func mapping(map: Map)
}
```
I should have used  "override class func newInstance(map: Map) -> Mappable? "
Isn't it a little bit strange to declare a static func and override a class func ? M'i missing something ?

**Comment by tristanhimmelman** [comment]
I agree it is a bit strange, but it is a work around. This is one of the reasons I want to change the protocol back to how it used to be.

**Comment by tristanhimmelman** [comment]
I just merged my protocol-update branch into the swift-2.0 branch. 

Thanks for your input :+1:

**Comment by benoit-pereira-da-silva** [comment]
I feel you are 100% right. And think we should adopt common patterns as possible.

``` swift 
public protocol NSCoding {
    
    public func encodeWithCoder(aCoder: NSCoder)
    public init?(coder aDecoder: NSCoder) // NS_DESIGNATED_INITIALIZER
}
```
Adopting the same approach will allow to convert seamlessly NSCoding compliant classes.

**Pull request closed without merging**
