### PR TITLE
Added support for nested arrays

### PR DESCRIPTION
**Pull request by ruben-samsonyan**
For example if json dictionary containes nested array, and user needs first element of array, path could be written like this: ["names.0"]. I have done this, because for my current project I coudn't get this kind of thing, but I needed, because I'm using openweathermap.org, and it retreives nested array for weather, and I needed to get weather descrition from that array. In my case for now I'm using it like this ["weather.0.description"]

### CODE REVIEW

**Comment by tristanhimmelman** [comment]
Hi @ruben-samsonyan, nice idea! Thanks for the pull request. 

It is important that new features, such as this one, are paired with a unit test to ensure functionality doesn't break down the line. Could you please add a test for this?

Thanks!

**Comment by ruben-samsonyan** [comment]
Hi Tristan,

Thank you for feedback. Of course I will do it.

Regards,
Ruben Samsonyan

**Comment by ruben-samsonyan** [comment]
Hi Tristan,

I have added test for nested arrays.

Regards,
Ruben Samsonyan

**Comment by tristanhimmelman** [comment]
Thanks @ruben-samsonyan for the addition :+1:

**Comment by ruben-samsonyan** [comment]
You are welcome

**Pull request merged**
