### PR TITLE
Added support for Swift 4.2 and Xcode 10

### PR DESCRIPTION
**Pull request by gcharita**
Contents of this pull request:
- Added support for Swift 4.2 without dropping support for Xcode 9.3 (and Xcode 9.4) and Swift 4.1 (in Xcode 9.3 and 9.4 warnings will remain due to the fact that the behaviour of IUO is not the same as Xcode 10 beta and as a result compilation fails in tests)
- Also fixed support for Xcode 9.2 and swift 4.0.

### CODE REVIEW

**Comment by Seonift** [comment]
i have an error in Xcode 10...
in EnumOperatior.swift : '<-' previously declared here

**Comment by gcharita** [comment]
Well, after creating this PR I realized the meaning of the conversation discussed in #976 about Swift 3 (and obviously Swift 4.1) in Xcode 10. So, this is not a perfect solution, unless we somehow specify the compiler to always use the latest version that supports.

**Comment by gcharita** [comment]
After taking a closer look to the [Compiler Version Directive](https://github.com/apple/swift-evolution/blob/master/proposals/0212-compiler-version-directive.md), I realized that there is a solution to this issue that doesn't need to change the `swift_version` in `.podspec` file.

This includes to change the compiler directives to:
```swift
#if !(swift(>=4.1.50) || (swift(>=3.4) && !swift(>=4.0)))
// Code targeting the Swift 4.1 compiler and below.
#endif
```
Of course this will add to the complexity of the directive check.

**Comment by andre991** [comment]
@gcharita Do you have any plans to merge this pull request?

**Comment by gcharita** [comment]
@andre991 I am not the maintainor of this repository. The only thing I can do is to apply the latest suggestion that I mentioned in the previous comment. (I believe it is the best solution so far)

**Comment by andre991** [comment]
Ok, thanks @gcharita.  @tristanhimmelman Do you have any plans to merge this pull request?

**Comment by ozgur** [comment]
For those who are building their apps using Xcode 10, can add the following statement into their `Podfile`:

```swift pod 'ObjectMapper', :git => 'https://github.com/alecdoconnor/ObjectMapper.git', :branch => 'Swift-4.2'`

**Comment by MortMerr** [comment]
@gcharita what do u think about fix warnings about deprecated flatMap in this pr?

**Comment by gcharita** [comment]
@MortMerr I already done this in https://github.com/Hearst-DD/ObjectMapper/pull/980/commits/bed2ff971f64f3aa1aa31a3448155f96a31afecd with backward compatibility.
There was 1 case in [Mapper.swift](https://github.com/Hearst-DD/ObjectMapper/pull/980/commits/bed2ff971f64f3aa1aa31a3448155f96a31afecd#diff-df0ab80b86decf5ebc24ab5f19f53868) file and 2 in [TransformOperators.swift](https://github.com/Hearst-DD/ObjectMapper/pull/980/commits/bed2ff971f64f3aa1aa31a3448155f96a31afecd#diff-b21287d017e282811775fd5697c7314c) file.

The rest of this was already fixed in https://github.com/Hearst-DD/ObjectMapper/commit/9fd123c5981027bfd73dcdddd7c465b4a67390fe by @tristanhimmelman. (I just added backward compatibility)

**Comment by tristanhimmelman** [comment]
Thanks for fix @gcharita ! 👍

**Comment by aaparth** [comment]
@gcharita  I tried it but still getting the error.

**Comment by gcharita** [comment]
@aaparth I am testing it in:
- Xcode 10 beta (swift 4.2, 4 and 3)
- Xcode 9.4.1 (swift 3.3 and 4.1)
- Xcode 9.2 (swift 3.2 and 4.0)

And everything looks ok.

Can you describe what exactly did you did and got the error?

**Comment by aaparth** [comment]
@gcharita Thanks for your contribution 
I got the 4.2 release from [https://github.com/Hearst-DD/ObjectMapper/releases](url) and everything works perfectly fine now.

**Comment by zhouhao27** [comment]
@gcharita I'm using swift 3 for Xcode 10 beta. Still got the same error message when I tried to use your commit **bed2ff9**. Here is what inside my pod file:

`pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper', :commit => 'bed2ff9'`

Do you know what could be the reason? Thanks.

**Comment by gcharita** [comment]
@zhouhao27 this is not the right commit.

Just install the latest version (which currently is 3.3.0) or change the commit, in your Podfile, to 
5985794

**Pull request merged**
