### PR TITLE
Ikesyo refactor from json to json

### PR DESCRIPTION
**Pull request by tristanhimmelman**

### CODE REVIEW

**Comment by ikesyo** [comment]
FYI: Xcode can parse triple-slash comments as documentation. :wink:

**Comment by tristanhimmelman** [comment]
Hahaha oops :). Good to know

**Comment by tristanhimmelman** [comment]
I am considering changing the map function definition in Mappable so that it doesn't conflict with the Swift map function. Do you have any suggestions on naming? I was thinking maybe one of the following:
```func mapping(map: Map)```
or
``` func mappable(map: Map)```

**Comment by ikesyo** [comment]
I agree with it. 👍

I prefer the former of the two.

**Pull request merged**
