### PR TITLE
Fixes build error on iOS9 beta 3

### PR DESCRIPTION
**Pull request by Torsph**
This pull request will fix the iOS9 beta 3 issues.

Closes https://github.com/Hearst-DD/ObjectMapper/issues/150

### CODE REVIEW

**Comment by jurvis** [comment]
using this fix temporarily until the PR is merged. Thanks @Torsph!

**Comment by schickling** [comment]
+1

**Comment by tristanhimmelman** [comment]
Thanks @Torsph :+1:

**Comment by Torsph** [comment]
Thanks for merging. Happy to help :)

**Pull request merged**
